### ISSUE TITLE
`join` with second argument starting with slash fails ?

### ISSUE THREAD

**Issue by vindarel** [fourier/ppath#1]
Hello, 

I tried the following:

    (ppath:join "http://" "/foo.html")

and it returns

    "/foo.html"

though I was expecting it to return `http://foo.html`. 

Bug found ?

Regards

**Comment by fourier** [comment]
Hi,
It is not really a bug, but not intended usage. ppath:join works on file system paths with their relevant assumptions, not on URIs. join works the following way: if any component starts with the leading slash, then it is assumed the root and any other leading components dropped.
